var exp=require("express")
var app=exp()
var bp=require("body-parser")
app.use(bp.json())
cat=require("./Services/catAPI")
reg=require("./Services/registerAPI")
search=require("./Services/searchAPI")
mob = require("./Services/mobileAPI")
app.use("/category",cat)
app.use("/register",reg)
app.use("/searchapi",search)
app.use("/moblile",mob)

app.listen(8888)
app.use(exp.static(__dirname))
console.log("Run..8888")