var exp=require("express")
var app=exp()
var bp=require("body-parser")
var fl= require("express-fileupload")
app.use(fl())
app.use(bp.json())
var cat=require("./Service/Routes/catAPI")
var scat=require("./Service/Routes/scatAPI")
var ssubcat=require("./Service/Routes/SubSubAPI")
var brd = require("./Service/Routes/brandAPI")
var prod=require("./Service/Routes/productAPI")
var business=require("./Service/Routes/businessAPI")
var log=require("./Service/Routes/loginAPI")
////////////////////////category Logic//////////////
app.use("/category",cat) 
app.use("/subcat",scat)
app.use("/ssubcat",ssubcat)
app.use("/brand",brd)
app.use("/poduct",prod)
app.use("/bus",business)
app.use("/log",log)
app.post("/fileapk",function(rrqq,rrss){
	console.log("hhhhhhh")
  })
app.listen(4444)
app.use(exp.static(__dirname))
console.log("Run..4444")